frontend:
  - changed-files:
      - any-glob-to-any-file: ['src/**', 'index.html', 'tests/e2e/**']
backend:
  - changed-files:
      - any-glob-to-any-file: ['backend/**']
ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**']
security:
  - changed-files:
      - any-glob-to-any-file: ['**/*auth*', '**/*security*', '**/*rbac*']
documentation:
  - changed-files:
      - any-glob-to-any-file: ['**/*.md']
